Repository chingu-voyages/v8-geckos-team-07, pull requests merged in 2019-04, with the labels that each got.

#38 Feature/add concurrently
  package.json
Labels: feature

#37 Fix/css setup merge
  client/src/components/Dashboard.js
  client/src/components/header-logged-in.js
  client/src/components/header.js
  client/src/containers/App.css
  client/src/containers/App.js
  client/src/containers/Layout.css
  client/src/containers/Layout.js
  client/src/images/bg.svg
  client/src/images/user-icon.svg
Labels: feature, fix/bug

#42 Newhabit
  client/package.json
  client/src/components/newhabit/NewHabit.js
  client/src/components/newhabit/newhabit.css
  client/src/containers/App.js
  routes/api/habits.js
Labels: feature

#45 specified node version in travis.yml
  .travis.yml
Labels: fix/bug

#47 Fix/backend routing
  README.md
  index.js
Labels: fix/bug

#48 Check in form started, some CSS Clean-up, first page circle styling applied, Google button styled
  client/src/components/About.js
  client/src/components/Login.js
  client/src/components/SocialButtonList.css
  client/src/components/SocialButtonList.js
  client/src/components/check-in.js
  client/src/containers/App.css
  client/src/containers/App.js
  client/src/containers/Layout.css
  client/src/containers/Layout.js
  client/src/images/btn_google_dark_normal_ios.svg
Labels: feature

#73 CSS clean up
  client/src/App.test.js
  client/src/components/Dashboard.css
  client/src/components/Dashboard.js
  client/src/components/Login.js
  client/src/components/NewHabit.js
  client/src/components/check-in.js
  client/src/components/header.js
  client/src/components/newhabit/newhabit.css
  client/src/containers/App.css
  client/src/containers/App.js
  client/src/containers/Layout.js
  client/src/index.css
Labels: task-item

#71 NewHabit Version 2.0
  client/src/components/Dashboard.js
  client/src/components/HabitSubmission.js
  client/src/components/NewHabit.js
  client/src/index.css
Labels: task-item

#74 Feature/user settings menu setup
  client/src/components/Dashboard.js
  client/src/components/Login.js
  client/src/components/NotFound.js
  client/src/components/SocialProfileList.css
  client/src/components/SocialProfileList.js
  client/src/components/footer.js
  client/src/components/header-logged-in.js
  client/src/containers/App.js
  client/src/containers/HeaderLoggedIn.js
  client/src/containers/Layout.js
  client/src/images/gecko.png
  client/src/index.css
Labels: feature

#75 New Habit 2.2 added close button
  client/src/components/NewHabit.js
  client/src/index.css
Labels: task-item

#83 Feature/widget calendar
  client/package.json
  client/public/index.html
  client/src/components/CalHM.js
  client/src/components/Dashboard.js
  client/src/components/Progress.js
  client/src/index.css
Labels: task-item

#84 🐛 - fixed spacing on NotFound component
  client/src/components/NotFound.js
Labels: fix/bug
